-- Preserve report/audit history while allowing a user parent row to be deleted.
ALTER TABLE users DROP FOREIGN KEY users_creator_fk;
ALTER TABLE users ADD CONSTRAINT users_creator_delete_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE todas DROP FOREIGN KEY todas_president_fk;
ALTER TABLE todas ADD CONSTRAINT todas_president_delete_fk FOREIGN KEY (president_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE authorized_personnel DROP FOREIGN KEY authorized_personnel_user_fk;
ALTER TABLE authorized_personnel ADD CONSTRAINT authorized_personnel_delete_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE students DROP FOREIGN KEY students_user_fk;
ALTER TABLE students ADD CONSTRAINT students_delete_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE drivers DROP FOREIGN KEY drivers_user_fk, DROP FOREIGN KEY drivers_creator_fk;
ALTER TABLE drivers ADD CONSTRAINT drivers_user_delete_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, ADD CONSTRAINT drivers_creator_delete_fk FOREIGN KEY (account_created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE complaints MODIFY student_user_id CHAR(36) NULL;
ALTER TABLE complaints DROP FOREIGN KEY complaints_student_fk, DROP FOREIGN KEY complaints_assignee_fk;
ALTER TABLE complaints ADD CONSTRAINT complaints_student_delete_fk FOREIGN KEY (student_user_id) REFERENCES users(id) ON DELETE SET NULL, ADD CONSTRAINT complaints_assignee_delete_fk FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE complaint_attachments MODIFY uploaded_by CHAR(36) NULL;
ALTER TABLE complaint_attachments DROP FOREIGN KEY attachments_user_fk;
ALTER TABLE complaint_attachments ADD CONSTRAINT attachments_user_delete_fk FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE complaint_status_history DROP FOREIGN KEY history_user_fk;
ALTER TABLE complaint_status_history ADD CONSTRAINT history_user_delete_fk FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE complaint_actions MODIFY action_taken_by CHAR(36) NULL;
ALTER TABLE complaint_actions DROP FOREIGN KEY actions_user_fk;
ALTER TABLE complaint_actions ADD CONSTRAINT actions_user_delete_fk FOREIGN KEY (action_taken_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE violations MODIFY confirmed_by CHAR(36) NULL;
ALTER TABLE violations DROP FOREIGN KEY violations_user_fk;
ALTER TABLE violations ADD CONSTRAINT violations_user_delete_fk FOREIGN KEY (confirmed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE notifications DROP FOREIGN KEY notifications_user_fk;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_delete_fk FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE audit_logs DROP FOREIGN KEY audit_user_fk;
ALTER TABLE audit_logs ADD CONSTRAINT audit_user_delete_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
