// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tricycle-reporting/AdminDashboard.tsx": () => import("../components/mockups/tricycle-reporting/AdminDashboard.tsx"),
  "./components/mockups/tricycle-reporting/AdminLanding.tsx": () => import("../components/mockups/tricycle-reporting/AdminLanding.tsx"),
  "./components/mockups/tricycle-reporting/Analytics.tsx": () => import("../components/mockups/tricycle-reporting/Analytics.tsx"),
  "./components/mockups/tricycle-reporting/Auth.tsx": () => import("../components/mockups/tricycle-reporting/Auth.tsx"),
  "./components/mockups/tricycle-reporting/DriverDirectory.tsx": () => import("../components/mockups/tricycle-reporting/DriverDirectory.tsx"),
  "./components/mockups/tricycle-reporting/DriverLanding.tsx": () => import("../components/mockups/tricycle-reporting/DriverLanding.tsx"),
  "./components/mockups/tricycle-reporting/Landing.tsx": () => import("../components/mockups/tricycle-reporting/Landing.tsx"),
  "./components/mockups/tricycle-reporting/MyReports.tsx": () => import("../components/mockups/tricycle-reporting/MyReports.tsx"),
  "./components/mockups/tricycle-reporting/Notifications.tsx": () => import("../components/mockups/tricycle-reporting/Notifications.tsx"),
  "./components/mockups/tricycle-reporting/OfficerDashboard.tsx": () => import("../components/mockups/tricycle-reporting/OfficerDashboard.tsx"),
  "./components/mockups/tricycle-reporting/OfficerLanding.tsx": () => import("../components/mockups/tricycle-reporting/OfficerLanding.tsx"),
  "./components/mockups/tricycle-reporting/PNPLanding.tsx": () => import("../components/mockups/tricycle-reporting/PNPLanding.tsx"),
  "./components/mockups/tricycle-reporting/PNPReview.tsx": () => import("../components/mockups/tricycle-reporting/PNPReview.tsx"),
  "./components/mockups/tricycle-reporting/Profile.tsx": () => import("../components/mockups/tricycle-reporting/Profile.tsx"),
  "./components/mockups/tricycle-reporting/PWAStates.tsx": () => import("../components/mockups/tricycle-reporting/PWAStates.tsx"),
  "./components/mockups/tricycle-reporting/ReportTracking.tsx": () => import("../components/mockups/tricycle-reporting/ReportTracking.tsx"),
  "./components/mockups/tricycle-reporting/ReviewWorkspace.tsx": () => import("../components/mockups/tricycle-reporting/ReviewWorkspace.tsx"),
  "./components/mockups/tricycle-reporting/RoleLanding.tsx": () => import("../components/mockups/tricycle-reporting/RoleLanding.tsx"),
  "./components/mockups/tricycle-reporting/StudentDashboard.tsx": () => import("../components/mockups/tricycle-reporting/StudentDashboard.tsx"),
  "./components/mockups/tricycle-reporting/StudentLanding.tsx": () => import("../components/mockups/tricycle-reporting/StudentLanding.tsx"),
  "./components/mockups/tricycle-reporting/SubmitReport.tsx": () => import("../components/mockups/tricycle-reporting/SubmitReport.tsx"),
  "./components/mockups/tricycle-reporting/Violations.tsx": () => import("../components/mockups/tricycle-reporting/Violations.tsx")
};
