import express from "express";
import cors from "cors";
import helmet from "helmet";
import multer from "multer";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import crypto from "node:crypto";
import pg from "pg";

const { Pool } = pg;
const app = express();
const pool = new Pool({
  connectionString: process.env.SUPABASE_DB_URL || process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined,
  max: Number(process.env.DB_CONNECTION_LIMIT || 10),
});

const roles = ["STUDENT", "DRIVER", "TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"];
const statuses = ["SUBMITTED", "RECEIVED", "UNDER_REVIEW", "VERIFIED", "REFERRED", "RESOLVED", "CLOSED"];
const transitions = {
  SUBMITTED: ["RECEIVED", "UNDER_REVIEW", "CLOSED"],
  RECEIVED: ["UNDER_REVIEW", "REFERRED", "CLOSED"],
  UNDER_REVIEW: ["VERIFIED", "REFERRED", "RESOLVED", "CLOSED"],
  VERIFIED: ["REFERRED", "RESOLVED", "CLOSED"],
  REFERRED: ["RESOLVED", "CLOSED"],
  RESOLVED: ["CLOSED"],
  CLOSED: [],
};
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024, files: 5 },
});

app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_ORIGIN?.split(",").map((v) => v.trim()) || true, allowedHeaders: ["Content-Type", "Authorization"], methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"] }));
app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));
app.use((req, _res, next) => {
  const routedPath = typeof req.query.__route === "string" ? req.query.__route : null;
  if (routedPath) {
    const query = new URLSearchParams(req.query);
    query.delete("__route");
    req.url = `${routedPath}${query.toString() ? `?${query}` : ""}`;
  } else if (req.url === "/api" || req.url === "/api/index.js") req.url = "/";
  else if (req.url.startsWith("/api/")) req.url = req.url.slice(4);
  next();
});
app.use((req, _res, next) => { console.info(JSON.stringify({ method: req.method, path: req.path })); next(); });

const error = (status, message, issues) => { const e = new Error(message); e.status = status; e.issues = issues; throw e; };
const uuid = () => crypto.randomUUID();
const safeUser = (u) => ({ id: u.id, fullName: u.full_name, email: u.email, role: u.role, status: u.status });
const body = (req) => (req.body && typeof req.body === "object" ? req.body : {});
const required = (data, fields) => fields.forEach((field) => { if (data[field] === undefined || data[field] === null || String(data[field]).trim() === "") error(400, `${field} is required.`); });
const validEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const bool = (value) => Boolean(value === true || value === 1 || value === "1" || value === "true");
const placeholders = (values, start = 1) => values.map((_, i) => `$${i + start}`).join(",");

async function q(text, params = [], client = pool) { const result = await client.query(text, params); return result.rows; }
async function one(text, params = [], client = pool) { return (await q(text, params, client))[0] || null; }
async function audit(userId, action, targetType = null, targetId = null, metadata = null, client = pool) { await q("INSERT INTO audit_logs (user_id, action, target_type, target_id, metadata) VALUES ($1,$2,$3,$4,$5)", [userId, action, targetType, targetId, metadata], client); }
async function notify(recipientId, type, message, complaintId = null, client = pool) { if (!recipientId) return; await q("INSERT INTO notifications (id, recipient_user_id, type, message, related_complaint_id) VALUES ($1,$2,$3,$4,$5)", [uuid(), recipientId, type, message, complaintId], client); }
async function notifyOfficers(type, message, complaintId, client = pool) { const officers = await q("SELECT id FROM users WHERE status='ACTIVE' AND role IN ('TODA_PRESIDENT','AUTHORIZED_PERSONNEL','SUPERADMIN','PNP')", [], client); for (const officer of officers) await notify(officer.id, type, message, complaintId, client); }

function tokenFor(user) { return jwt.sign({ sub: user.id, role: user.role }, process.env.JWT_SECRET, { expiresIn: "8h" }); }
async function auth(req, _res, next) {
  try {
    const header = req.headers.authorization || "";
    if (!header.startsWith("Bearer ")) return error(401, "Authentication required.");
    const payload = jwt.verify(header.slice(7), process.env.JWT_SECRET);
    const user = await one("SELECT * FROM users WHERE id=$1 LIMIT 1", [payload.sub]);
    if (!user || user.status !== "ACTIVE") return error(401, "Account is not active.");
    req.user = user; next();
  } catch (e) { next(e.status ? e : Object.assign(new Error("Invalid or expired session."), { status: 401 })); }
}
const rolesOnly = (...allowed) => (req, _res, next) => allowed.includes(req.user?.role) ? next() : next(Object.assign(new Error("You are not authorized to access this resource."), { status: 403 }));
async function transaction(work) { const client = await pool.connect(); try { await client.query("BEGIN"); const value = await work(client); await client.query("COMMIT"); return value; } catch (e) { await client.query("ROLLBACK"); throw e; } finally { client.release(); } }

async function todaIds(user, client = pool) { if (user.role !== "TODA_PRESIDENT") return []; return (await q("SELECT id FROM todas WHERE president_user_id=$1 AND is_active=1 ORDER BY id", [user.id], client)).map((r) => r.id); }
async function canAccess(complaint, user, client = pool) {
  if (["AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"].includes(user.role)) return true;
  if (user.role === "STUDENT") return complaint.student_user_id === user.id;
  if (user.role === "DRIVER") return Boolean(await one("SELECT id FROM drivers WHERE id=$1 AND user_id=$2", [complaint.driver_id, user.id], client));
  if (user.role === "TODA_PRESIDENT") return Boolean(await one("SELECT d.id FROM drivers d JOIN todas t ON t.id=d.toda_id WHERE d.id=$1 AND t.president_user_id=$2 AND t.is_active=1", [complaint.driver_id, user.id], client));
  return false;
}
async function complaintOr404(id, user, client = pool) { const complaint = await one("SELECT * FROM complaints WHERE id=$1 LIMIT 1", [id], client); if (!complaint) error(404, "Complaint not found."); if (!(await canAccess(complaint, user, client))) error(403, "You are not authorized to view this complaint."); return complaint; }
async function publicComplaint(id, client = pool) {
  const complaint = await one("SELECT * FROM complaints WHERE id=$1", [id], client);
  if (!complaint) return null;
  const [driver, category, history, actions, attachments, violation] = await Promise.all([
    one("SELECT * FROM drivers WHERE id=$1", [complaint.driver_id], client),
    one("SELECT * FROM complaint_categories WHERE id=$1", [complaint.category_id], client),
    q("SELECT * FROM complaint_status_history WHERE complaint_id=$1 ORDER BY created_at", [id], client),
    q("SELECT a.*, u.full_name AS \"authorName\", u.role AS \"authorRole\" FROM complaint_actions a LEFT JOIN users u ON u.id=a.action_taken_by WHERE a.complaint_id=$1 ORDER BY a.created_at DESC", [id], client),
    q("SELECT id, original_name AS \"originalName\", mime_type AS \"mimeType\", size_bytes AS \"sizeBytes\", created_at AS \"createdAt\" FROM complaint_attachments WHERE complaint_id=$1", [id], client),
    one("SELECT * FROM violations WHERE complaint_id=$1 LIMIT 1", [id], client),
  ]);
  return { complaint, driver, category, history, actions, attachments, violation };
}

async function storageUpload(file, folder) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const bucket = process.env.SUPABASE_STORAGE_BUCKET || "uploads";
  if (!url || !key) error(500, "Online file storage is not configured.");
  const ext = (file.originalname.match(/\.[a-z0-9]+$/i) || [""])[0].toLowerCase();
  const path = `${folder}/${uuid()}${ext}`;
  const response = await fetch(`${url}/storage/v1/object/${bucket}/${path}`, { method: "POST", headers: { Authorization: `Bearer ${key}`, apikey: key, "Content-Type": file.mimetype, "x-upsert": "false" }, body: file.buffer });
  if (!response.ok) error(500, "Unable to save the uploaded file.");
  return { path, url: `${url}/storage/v1/object/authenticated/${bucket}/${path}` };
}

app.get(["/health", "/healthz", "/api/health", "/api/healthz"], async (_req, res, next) => { try { await q("SELECT 1"); res.json({ status: "ok" }); } catch (e) { next(e); } });

app.post("/auth/register", async (req, res, next) => { try {
  const data = body(req); required(data, ["fullName", "email", "password", "confirmPassword"]); const role = String(data.role || "STUDENT").toUpperCase();
  if (!["STUDENT", "DRIVER"].includes(role)) error(400, "Only student and driver accounts can self-register.");
  if (!validEmail(data.email)) error(400, "Use a valid email address."); if (String(data.password).length < 8) error(400, "Password must be at least 8 characters."); if (data.password !== data.confirmPassword) error(400, "Passwords do not match.");
  if (role === "STUDENT") required(data, ["studentId"]); else required(data, ["driverCode", "tricycleIdentifier"]);
  const result = await transaction(async (client) => {
    const userId = uuid(); const email = String(data.email).toLowerCase(); const hash = await bcrypt.hash(data.password, 12);
    await q("INSERT INTO users (id,full_name,email,password_hash,role,contact_number) VALUES ($1,$2,$3,$4,$5,$6)", [userId, String(data.fullName).trim(), email, hash, role, data.contactNumber || null], client);
    if (role === "STUDENT") await q("INSERT INTO students (user_id,student_id,program,year_level) VALUES ($1,$2,$3,$4)", [userId, String(data.studentId).trim(), data.program || null, data.yearLevel || null], client);
    else { const toda = await one("SELECT id FROM todas WHERE is_active=1 ORDER BY id LIMIT 1", [], client); if (!toda) error(400, "No active designated location is available. Ask Authorized Personnel to create a location first."); await q("INSERT INTO drivers (user_id,toda_id,full_name,driver_code,tricycle_identifier,route_area,contact_number) VALUES ($1,$2,$3,$4,$5,$6,$7)", [userId, toda.id, String(data.fullName).trim(), String(data.driverCode).trim(), String(data.tricycleIdentifier).trim(), data.routeArea || null, data.contactNumber || null], client); }
    await audit(userId, "REGISTER", "users", userId, null, client); return await one("SELECT * FROM users WHERE id=$1", [userId], client);
  });
  res.status(201).json({ user: safeUser(result), token: tokenFor(result) });
} catch (e) { next(e); } });

app.post("/auth/login", async (req, res, next) => { try { const data = body(req); const account = String(data.email || data.username || "").toLowerCase(); const user = await one("SELECT * FROM users WHERE email=$1 OR username=$1 LIMIT 1", [account]); if (!user || user.status !== "ACTIVE" || !(await bcrypt.compare(String(data.password || ""), user.password_hash))) error(401, "Invalid email or password."); await audit(user.id, "LOGIN", "users", user.id); res.json({ user: safeUser(user), token: tokenFor(user) }); } catch (e) { next(e); } });
app.post("/auth/logout", auth, async (req, res, next) => { try { await audit(req.user.id, "LOGOUT", "users", req.user.id); res.json({ ok: true }); } catch (e) { next(e); } });

app.post("/users/authorized-personnel", auth, rolesOnly("SUPERADMIN"), async (req, res, next) => { try { const data = body(req); const role = data.role === "PNP" ? "PNP" : "AUTHORIZED_PERSONNEL"; required(data, ["fullName", "password"]); if (!data.email && !data.username) error(400, "Email or username is required."); const user = await createManagedUser(data, role, req.user.id); await transaction(async (client) => { await q("INSERT INTO authorized_personnel (user_id,personnel_type,office_name,position_title) VALUES ($1,$2,$3,$4)", [user.id, data.personnelType || "BARANGAY_STAFF", data.officeName || "Barangay Old Sagay", data.positionTitle || null], client); await audit(req.user.id, "AUTHORIZED_PERSONNEL_CREATE", "users", user.id, null, client); }); res.status(201).json({ user: safeUser(user) }); } catch (e) { next(e); } });
async function createManagedUser(data, role, createdBy, client = pool) { required(data, ["fullName", "password"]); if (data.email && !validEmail(data.email)) error(400, "Use a valid email address."); if (data.password.length < 8) error(400, "Password must be at least 8 characters."); const id = uuid(); await q("INSERT INTO users (id,full_name,email,username,password_hash,role,contact_number,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)", [id, String(data.fullName).trim(), data.email ? String(data.email).toLowerCase() : null, data.username ? String(data.username).toLowerCase() : null, await bcrypt.hash(data.password, 12), role, data.contactNumber || null, createdBy], client); return one("SELECT * FROM users WHERE id=$1", [id], client); }

app.post("/users/toda-presidents", auth, rolesOnly("AUTHORIZED_PERSONNEL"), async (req, res, next) => { try { const data = body(req); required(data, ["todaId"]); const toda = await one("SELECT * FROM todas WHERE id=$1", [Number(data.todaId)]); if (!toda) error(404, "TODA not found."); if (toda.president_user_id) error(409, "This TODA already has a president account. Edit or delete the existing account first."); const result = await transaction(async (client) => { const user = await createManagedUser(data, "TODA_PRESIDENT", req.user.id, client); await q("UPDATE todas SET president_user_id=$1 WHERE id=$2", [user.id, Number(data.todaId)], client); await audit(req.user.id, "TODA_PRESIDENT_CREATE", "users", user.id, { todaId: Number(data.todaId) }, client); return user; }); res.status(201).json({ user: safeUser(result) }); } catch (e) { next(e); } });
app.get("/users/toda-presidents", auth, rolesOnly("AUTHORIZED_PERSONNEL", "SUPERADMIN"), async (_req, res, next) => { try { res.json({ presidents: await q("SELECT u.id,u.full_name AS \"fullName\",u.email,u.status,t.id AS \"todaId\",t.name AS \"todaName\" FROM users u JOIN todas t ON t.president_user_id=u.id WHERE u.role='TODA_PRESIDENT' ORDER BY t.name") }); } catch (e) { next(e); } });
app.patch("/users/toda-presidents/:id", auth, rolesOnly("AUTHORIZED_PERSONNEL"), async (req, res, next) => { try { const data = body(req); const id = req.params.id; const target = await one("SELECT id FROM users WHERE id=$1 AND role='TODA_PRESIDENT'", [id]); if (!target) error(404, "TODA President account not found."); if (!data.fullName || !validEmail(data.email)) error(400, "Full name and valid email are required."); await transaction(async (client) => { if (data.todaId) { const toda = await one("SELECT * FROM todas WHERE id=$1", [Number(data.todaId)], client); if (!toda) error(404, "TODA not found."); if (toda.president_user_id && toda.president_user_id !== id) error(409, "That TODA already has a different president account."); await q("UPDATE todas SET president_user_id=NULL WHERE president_user_id=$1", [id], client); await q("UPDATE todas SET president_user_id=$1 WHERE id=$2", [id, Number(data.todaId)], client); } await q("UPDATE users SET full_name=$1,email=$2,status=COALESCE($3,status),password_hash=COALESCE($4,password_hash) WHERE id=$5", [String(data.fullName).trim(), String(data.email).toLowerCase(), data.status || null, data.password ? await bcrypt.hash(data.password, 12) : null, id], client); await audit(req.user.id, "TODA_PRESIDENT_UPDATE", "users", id, null, client); }); res.json({ ok: true }); } catch (e) { next(e); } });
app.delete("/users/toda-presidents/:id", auth, rolesOnly("AUTHORIZED_PERSONNEL"), async (req, res, next) => { try { const id = req.params.id; if (!(await one("SELECT id FROM users WHERE id=$1 AND role='TODA_PRESIDENT'", [id]))) error(404, "TODA President account not found."); await transaction(async (client) => { await q("UPDATE todas SET president_user_id=NULL WHERE president_user_id=$1", [id], client); await q("DELETE FROM users WHERE id=$1", [id], client); await audit(req.user.id, "TODA_PRESIDENT_DELETE", "users", id, null, client); }); res.json({ ok: true }); } catch (e) { next(e); } });

app.post("/drivers/accounts", auth, rolesOnly("TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN"), async (req, res, next) => { try { const data = body(req); required(data, ["fullName", "driverCode", "tricycleIdentifier", "password"]); if (req.user.role === "TODA_PRESIDENT" && data.contactNumber) error(400, "TODA president-created driver accounts are only for drivers without a phone number."); const assigned = req.user.role === "TODA_PRESIDENT" ? (await todaIds(req.user))[0] : Number(data.todaId); if (!assigned) error(400, "todaId is required."); if (!(await one("SELECT id FROM todas WHERE id=$1 AND is_active=1", [assigned]))) error(400, "A valid active TODA is required."); const result = await transaction(async (client) => { const user = await createManagedUser(data, "DRIVER", req.user.id, client); await q("INSERT INTO drivers (user_id,toda_id,full_name,driver_code,tricycle_identifier,plate_number,route_area,contact_number,account_created_by,account_creation_reason) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", [user.id, assigned, data.fullName.trim(), data.driverCode.trim(), data.tricycleIdentifier.trim(), data.plateNumber || null, data.routeArea || null, data.contactNumber || null, req.user.id, data.contactNumber ? "AUTHORIZED_CREATED" : "TODA_CREATED_NO_PHONE"], client); await audit(req.user.id, "DRIVER_ACCOUNT_CREATE", "users", user.id, null, client); return user; }); res.status(201).json({ user: safeUser(result) }); } catch (e) { next(e); } });

app.get("/todas", auth, rolesOnly("AUTHORIZED_PERSONNEL", "TODA_PRESIDENT", "SUPERADMIN"), async (req, res, next) => { try { const rows = req.user.role === "TODA_PRESIDENT" ? await q("SELECT id,name,barangay,city,province,president_user_id AS \"presidentUserId\" FROM todas WHERE president_user_id=$1 ORDER BY name", [req.user.id]) : await q("SELECT id,name,barangay,city,province,president_user_id AS \"presidentUserId\" FROM todas ORDER BY name"); res.json({ todas: rows }); } catch (e) { next(e); } });
app.post("/todas", auth, rolesOnly("AUTHORIZED_PERSONNEL"), async (req, res, next) => { try { const data = body(req); required(data, ["barangay", "city", "province"]); const name = String(data.name || `${data.barangay}, ${data.city}`).trim(); const row = await one("INSERT INTO todas (name,barangay,city,province) VALUES ($1,$2,$3,$4) RETURNING id,name,barangay,city,province,president_user_id AS \"presidentUserId\"", [name, data.barangay.trim(), data.city.trim(), data.province.trim()]); await audit(req.user.id, "TODA_CREATE", "todas", String(row.id)); res.status(201).json({ toda: row }); } catch (e) { next(e); } });

app.get("/me", auth, async (req, res, next) => { try { let profile = { contactNumber: req.user.contact_number || null }; if (req.user.role === "STUDENT") profile = { ...profile, ...(await one("SELECT student_id AS \"studentId\",program,year_level AS \"yearLevel\",campus FROM students WHERE user_id=$1", [req.user.id]) || {}) }; if (req.user.role === "DRIVER") profile = { ...profile, ...(await one("SELECT d.driver_code AS \"driverCode\",d.tricycle_identifier AS \"tricycleIdentifier\",d.route_area AS \"routeArea\",t.name AS \"todaName\",t.barangay,t.city,t.province FROM drivers d LEFT JOIN todas t ON t.id=d.toda_id WHERE d.user_id=$1", [req.user.id]) || {}) }; const preferences = await one("SELECT report_updates AS updates,reminders FROM user_preferences WHERE user_id=$1", [req.user.id]); res.json({ user: safeUser(req.user), profile, preferences: { updates: preferences ? bool(preferences.updates) : true, reminders: preferences ? bool(preferences.reminders) : false } }); } catch (e) { next(e); } });
app.patch("/me", auth, async (req, res, next) => { try { const data = body(req); const name = String(data.fullName || req.user.full_name).trim(); const email = String(data.email || req.user.email || "").trim().toLowerCase(); if (!name) error(400, "Full name is required."); if (email && !validEmail(email)) error(400, "Use a valid email address."); const user = await one("UPDATE users SET full_name=$1,email=NULLIF($2,'') WHERE id=$3 RETURNING *", [name, email, req.user.id]); await audit(req.user.id, "PROFILE_UPDATE", "users", req.user.id); res.json({ user: safeUser(user) }); } catch (e) { next(e); } });
app.get("/me/photo", auth, async (req, res, next) => { try { const user = await one("SELECT profile_photo_path FROM users WHERE id=$1", [req.user.id]); if (!user?.profile_photo_path) error(404, "No profile photo has been uploaded."); const response = await fetch(user.profile_photo_path, { headers: { Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`, apikey: process.env.SUPABASE_SERVICE_ROLE_KEY } }); if (!response.ok) error(404, "No profile photo has been uploaded."); res.setHeader("Content-Type", response.headers.get("content-type") || "application/octet-stream"); res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0"); res.send(Buffer.from(await response.arrayBuffer())); } catch (e) { next(e); } });
app.post("/me/photo", auth, upload.single("photo"), async (req, res, next) => { try { const file = req.file; if (!file) error(400, "Choose a profile image to upload."); if (!["image/jpeg", "image/png", "image/webp"].includes(file.mimetype)) error(400, "Only JPG, PNG, and WEBP profile images are supported."); const stored = await storageUpload(file, `profile-photos/${req.user.id}`); await q("UPDATE users SET profile_photo_path=$1 WHERE id=$2", [stored.url, req.user.id]); await audit(req.user.id, "PROFILE_PHOTO_UPLOAD", "users", req.user.id, { mimeType: file.mimetype }); res.json({ ok: true }); } catch (e) { next(e); } });
app.delete("/me/photo", auth, async (req, res, next) => { try { await q("UPDATE users SET profile_photo_path=NULL WHERE id=$1", [req.user.id]); await audit(req.user.id, "PROFILE_PHOTO_DELETE", "users", req.user.id); res.json({ ok: true }); } catch (e) { next(e); } });
app.post("/me/password", auth, async (req, res, next) => { try { const data = body(req); if (!(await bcrypt.compare(String(data.currentPassword || ""), req.user.password_hash))) error(400, "Current password is incorrect."); if (String(data.newPassword || "").length < 8) error(400, "New password must be at least 8 characters."); await q("UPDATE users SET password_hash=$1 WHERE id=$2", [await bcrypt.hash(data.newPassword, 12), req.user.id]); await audit(req.user.id, "PASSWORD_UPDATE", "users", req.user.id); res.json({ ok: true }); } catch (e) { next(e); } });
app.patch("/me/preferences", auth, async (req, res, next) => { try { const data = body(req); const values = [req.user.id, bool(data.updates) ? 1 : 0, bool(data.reminders) ? 1 : 0]; await q("INSERT INTO user_preferences (user_id,report_updates,reminders) VALUES ($1,$2,$3) ON CONFLICT (user_id) DO UPDATE SET report_updates=EXCLUDED.report_updates,reminders=EXCLUDED.reminders", values); res.json({ preferences: { updates: Boolean(values[1]), reminders: Boolean(values[2]) } }); } catch (e) { next(e); } });

app.get("/drivers", auth, async (req, res, next) => { try { const search = `%${String(req.query.search || "")}%`; res.json({ drivers: await q("SELECT d.id,d.full_name AS \"fullName\",d.driver_code AS \"driverCode\",d.tricycle_identifier AS \"tricycleIdentifier\",d.plate_number AS \"plateNumber\",d.route_area AS \"routeArea\",d.contact_number AS \"contactNumber\",d.is_active AS \"isActive\",(SELECT COUNT(*) FROM complaints c WHERE c.driver_id=d.id) AS \"reportCount\",(SELECT COUNT(*) FROM violations v WHERE v.driver_id=d.id) AS \"confirmedViolationCount\" FROM drivers d WHERE d.is_active=1 AND (d.full_name ILIKE $1 OR d.driver_code ILIKE $1 OR d.tricycle_identifier ILIKE $1) ORDER BY d.full_name LIMIT 100", [search]) }); } catch (e) { next(e); } });
app.get("/drivers/:id", auth, rolesOnly("AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const id = Number(req.params.id); const driver = await one("SELECT id,full_name AS \"fullName\",driver_code AS \"driverCode\" FROM drivers WHERE id=$1 AND is_active=1", [id]); if (!driver) error(404, "Driver not found."); const reports = await q("SELECT c.reference_number AS id,c.incident_date AS date,cat.name AS category,LEFT(c.description,180) AS summary,c.status FROM complaints c JOIN complaint_categories cat ON cat.id=c.category_id WHERE c.driver_id=$1 ORDER BY c.created_at DESC", [id]); const violations = await q("SELECT CONCAT('VIO-',v.id) AS reference,v.confirmation_date AS date,v.violation_category AS finding,COALESCE(v.remarks,'Confirmed violation') AS action FROM violations v WHERE v.driver_id=$1 ORDER BY v.confirmation_date DESC", [id]); res.json({ driver, reports, violations }); } catch (e) { next(e); } });
app.get("/categories", auth, async (_req, res, next) => { try { res.json({ categories: await q("SELECT id,name,description FROM complaint_categories WHERE is_active=1 ORDER BY name") }); } catch (e) { next(e); } });

app.post("/complaints", auth, rolesOnly("STUDENT"), upload.array("attachments", 5), async (req, res, next) => { try { const data = body(req); required(data, ["driverId", "categoryId", "incidentDate", "incidentTime", "location", "description"]); if (String(data.description).length < 15) error(400, "Description must be at least 15 characters."); const files = req.files || []; const result = await transaction(async (client) => { if (!(await one("SELECT id FROM drivers WHERE id=$1 AND is_active=1", [Number(data.driverId)], client)) || !(await one("SELECT id FROM complaint_categories WHERE id=$1 AND is_active=1", [Number(data.categoryId)], client))) error(400, "Invalid driver or category."); const id = uuid(); const reference = `TRC-${new Date().getFullYear()}-${crypto.randomInt(100000, 999999)}`; await q("INSERT INTO complaints (id,reference_number,student_user_id,driver_id,category_id,status,incident_date,incident_time,location,description) VALUES ($1,$2,$3,$4,$5,'SUBMITTED',$6,$7,$8,$9)", [id, reference, req.user.id, Number(data.driverId), Number(data.categoryId), data.incidentDate, data.incidentTime, String(data.location).trim(), String(data.description).trim()], client); await q("INSERT INTO complaint_status_history (complaint_id,previous_status,new_status,changed_by,remarks) VALUES ($1,NULL,'SUBMITTED',$2,$3)", [id, req.user.id, "Complaint submitted by student."], client); for (const file of files) { const allowed = ["image/jpeg", "image/png", "image/webp", "application/pdf"]; if (!allowed.includes(file.mimetype)) error(400, "Invalid attachment type or size."); const stored = await storageUpload(file, `complaints/${id}`); await q("INSERT INTO complaint_attachments (id,complaint_id,original_name,stored_name,mime_type,size_bytes,storage_path,uploaded_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)", [uuid(), id, file.originalname.split(/[\\/]/).pop(), stored.path, file.mimetype, file.size, stored.url, req.user.id], client); } await audit(req.user.id, "COMPLAINT_CREATE", "complaints", id, null, client); return { id, reference }; }); await notify(req.user.id, "COMPLAINT_SUBMITTED", `Complaint ${result.reference} was submitted.`, result.id); await notifyOfficers("NEW_COMPLAINT", `New complaint ${result.reference} requires review.`, result.id); res.status(201).json({ complaint: { id: result.id, referenceNumber: result.reference, status: "SUBMITTED" } }); } catch (e) { next(e); } });

app.get("/complaints", auth, async (req, res, next) => { try { let sql = "SELECT c.id,c.reference_number AS \"referenceNumber\",c.status,c.incident_date AS \"incidentDate\",c.incident_time AS \"incidentTime\",c.location,c.description,c.driver_id AS \"driverId\",d.full_name AS \"driverName\",c.category_id AS \"categoryId\",cat.name AS \"categoryName\",c.created_at AS \"createdAt\",(SELECT MAX(h.created_at) FROM complaint_status_history h WHERE h.complaint_id=c.id AND h.new_status IN ('RESOLVED','CLOSED')) AS \"resolvedAt\" FROM complaints c JOIN drivers d ON d.id=c.driver_id JOIN complaint_categories cat ON cat.id=c.category_id"; const params = []; const where = []; if (req.user.role === "STUDENT") { where.push(`c.student_user_id=$${params.length + 1}`); params.push(req.user.id); } else if (req.user.role === "DRIVER") { where.push(`c.driver_id IN (SELECT id FROM drivers WHERE user_id=$${params.length + 1})`); params.push(req.user.id); } else if (req.user.role === "TODA_PRESIDENT") { const ids = await todaIds(req.user); if (!ids.length) return res.json({ complaints: [] }); where.push(`d.toda_id IN (${placeholders(ids, params.length + 1)})`); params.push(...ids); } if (where.length) sql += ` WHERE ${where.join(" AND ")}`; sql += " ORDER BY c.created_at DESC LIMIT 100"; res.json({ complaints: await q(sql, params) }); } catch (e) { next(e); } });
app.get("/complaints/:id", auth, async (req, res, next) => { try { const complaint = await complaintOr404(req.params.id, req.user); res.json(await publicComplaint(complaint.id)); } catch (e) { next(e); } });
app.get("/attachments/:id", auth, async (req, res, next) => { try { const attachment = await one("SELECT * FROM complaint_attachments WHERE id=$1", [req.params.id]); if (!attachment) error(404, "Attachment not found."); const complaint = await complaintOr404(attachment.complaint_id, req.user); if (!attachment.storage_path) error(404, "Attachment file not found."); const response = await fetch(attachment.storage_path, { headers: process.env.SUPABASE_SERVICE_ROLE_KEY ? { Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`, apikey: process.env.SUPABASE_SERVICE_ROLE_KEY } : {} }); if (!response.ok) error(404, "Attachment file not found."); res.setHeader("Content-Type", attachment.mime_type); res.setHeader("Content-Disposition", `attachment; filename=\"${String(attachment.original_name).replace(/\"/g, "") }\"`); res.send(Buffer.from(await response.arrayBuffer())); } catch (e) { next(e); } });

app.patch("/complaints/:id/status", auth, rolesOnly("TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const data = body(req); if (!statuses.includes(data.status)) error(400, "Invalid status."); const complaint = await complaintOr404(req.params.id, req.user); if (!transitions[complaint.status].includes(data.status)) error(400, "That status transition is not allowed."); await transaction(async (client) => { await q("UPDATE complaints SET status=$1 WHERE id=$2", [data.status, complaint.id], client); await q("INSERT INTO complaint_status_history (complaint_id,previous_status,new_status,changed_by,remarks) VALUES ($1,$2,$3,$4,$5)", [complaint.id, complaint.status, data.status, req.user.id, data.remarks || null], client); await audit(req.user.id, "COMPLAINT_STATUS_UPDATE", "complaints", complaint.id, { from: complaint.status, to: data.status }, client); }); await notify(complaint.student_user_id, "COMPLAINT_STATUS_UPDATED", `Complaint ${complaint.reference_number} is now ${data.status.replaceAll("_", " ")}.`, complaint.id); res.json({ complaint: { id: complaint.id, referenceNumber: complaint.reference_number, status: data.status } }); } catch (e) { next(e); } });
app.post("/complaints/:id/actions", auth, rolesOnly("AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const data = body(req); required(data, ["actionType", "description"]); const complaint = await complaintOr404(req.params.id, req.user); const action = await one("INSERT INTO complaint_actions (complaint_id,action_type,description,action_taken_by) VALUES ($1,$2,$3,$4) RETURNING id", [complaint.id, data.actionType, data.description, req.user.id]); await audit(req.user.id, "COMPLAINT_ACTION_CREATE", "complaint_actions", String(action.id), { complaintId: complaint.id }); await notify(complaint.student_user_id, "COMPLAINT_ACTION_RECORDED", `An action was recorded for complaint ${complaint.reference_number}.`, complaint.id); res.status(201).json({ action: { id: Number(action.id) } }); } catch (e) { next(e); } });
app.post("/complaints/:id/violations", auth, rolesOnly("TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const data = body(req); const complaint = await complaintOr404(req.params.id, req.user); if (!["VERIFIED", "RESOLVED", "CLOSED"].includes(complaint.status)) error(400, "A confirmed violation can only be recorded after appropriate review."); if (await one("SELECT id FROM violations WHERE complaint_id=$1", [complaint.id])) error(409, "A violation has already been recorded for this report."); required(data, ["violationCategory", "description"]); const violation = await one("INSERT INTO violations (driver_id,complaint_id,violation_category,description,confirmed_by,remarks) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id", [complaint.driver_id, complaint.id, data.violationCategory, data.description, req.user.id, data.remarks || null]); await audit(req.user.id, "VIOLATION_CREATE", "violations", String(violation.id), { complaintId: complaint.id }); res.status(201).json({ violation: { id: Number(violation.id) } }); } catch (e) { next(e); } });

app.get("/notifications", auth, async (req, res, next) => { try { const rows = await q("SELECT n.id,n.type,n.message,n.related_complaint_id AS \"relatedComplaintId\",c.reference_number AS \"reportReference\",n.read_at AS \"readAt\",n.created_at AS \"createdAt\" FROM notifications n LEFT JOIN complaints c ON c.id=n.related_complaint_id WHERE n.recipient_user_id=$1 ORDER BY n.created_at DESC LIMIT 100", [req.user.id]); res.json({ notifications: rows, unread: rows.filter((r) => !r.readAt).length }); } catch (e) { next(e); } });
app.patch("/notifications/:id/read", auth, async (req, res, next) => { try { await q("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=$1 AND recipient_user_id=$2", [req.params.id, req.user.id]); res.json({ ok: true }); } catch (e) { next(e); } });
app.patch("/notifications/read-all", auth, async (req, res, next) => { try { await q("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE recipient_user_id=$1", [req.user.id]); res.json({ ok: true }); } catch (e) { next(e); } });
app.get("/violations", auth, async (req, res, next) => { try { let sql = "SELECT v.id,v.complaint_id AS \"complaintId\",d.full_name AS driver,c.reference_number AS \"relatedReport\",v.violation_category AS type,DATE(v.confirmation_date) AS \"dateValue\",v.description AS summary,COALESCE(v.remarks,'') AS action FROM violations v JOIN drivers d ON d.id=v.driver_id JOIN complaints c ON c.id=v.complaint_id"; const params = []; if (req.user.role === "DRIVER") { sql += " WHERE d.user_id=$1"; params.push(req.user.id); } else if (req.user.role === "TODA_PRESIDENT") { const ids = await todaIds(req.user); if (!ids.length) return res.json({ violations: [] }); sql += ` WHERE d.toda_id IN (${placeholders(ids)})`; params.push(...ids); } sql += " ORDER BY v.confirmation_date DESC LIMIT 100"; res.json({ violations: await q(sql, params) }); } catch (e) { next(e); } });
app.get("/dashboard/stats", auth, rolesOnly("TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const scope = req.user.role === "TODA_PRESIDENT" ? await todaIds(req.user) : null; const params = scope; const condition = scope ? ` WHERE d.toda_id IN (${placeholders(scope)})` : ""; const byStatus = await q(`SELECT c.status,COUNT(*) AS total FROM complaints c JOIN drivers d ON d.id=c.driver_id${condition} GROUP BY c.status`, params || []); const row = await one(`SELECT COUNT(*) AS total FROM violations v JOIN complaints c ON c.id=v.complaint_id JOIN drivers d ON d.id=c.driver_id${condition}`, params || []); res.json({ byStatus, confirmedViolations: Number(row.total) }); } catch (e) { next(e); } });
app.get("/reports/summary", auth, rolesOnly("TODA_PRESIDENT", "AUTHORIZED_PERSONNEL", "SUPERADMIN", "PNP"), async (req, res, next) => { try { const scope = req.user.role === "TODA_PRESIDENT" ? await todaIds(req.user) : null; const params = scope || []; const join = scope ? ` JOIN drivers d ON d.id=r.driver_id WHERE d.toda_id IN (${placeholders(scope)})` : ""; const byStatus = await q(`SELECT r.status AS label,COUNT(*) AS total FROM complaints r${join} GROUP BY r.status`, params); const byCategory = await q(`SELECT cc.name AS label,COUNT(*) AS total FROM complaints r JOIN complaint_categories cc ON cc.id=r.category_id${scope ? ` JOIN drivers d ON d.id=r.driver_id WHERE d.toda_id IN (${placeholders(scope)})` : ""} GROUP BY cc.name`, params); const monthly = await q(`SELECT TO_CHAR(r.created_at,'YYYY-MM') AS label,COUNT(*) AS total FROM complaints r${join} GROUP BY TO_CHAR(r.created_at,'YYYY-MM')`, params); res.json({ byStatus, byCategory, monthly }); } catch (e) { next(e); } });

app.get("/admin/directory", auth, rolesOnly("SUPERADMIN"), async (_req, res, next) => { try { const [students, drivers, personnel, presidents] = await Promise.all([q("SELECT u.id,u.full_name AS \"fullName\",u.email,u.status,u.created_at AS \"createdAt\",s.student_id AS \"studentId\",s.program,s.year_level AS \"yearLevel\",s.campus FROM users u JOIN students s ON s.user_id=u.id WHERE u.role='STUDENT' ORDER BY u.created_at DESC"), q("SELECT u.id,u.full_name AS \"fullName\",u.email,u.status,u.created_at AS \"createdAt\",d.driver_code AS \"driverCode\",d.tricycle_identifier AS \"tricycleIdentifier\",d.route_area AS \"routeArea\",t.name AS \"todaName\" FROM drivers d LEFT JOIN users u ON u.id=d.user_id JOIN todas t ON t.id=d.toda_id ORDER BY d.created_at DESC"), q("SELECT u.id,u.full_name AS \"fullName\",u.email,u.role,u.status,u.created_at AS \"createdAt\",p.personnel_type AS \"personnelType\",p.office_name AS \"officeName\",p.position_title AS \"positionTitle\" FROM users u JOIN authorized_personnel p ON p.user_id=u.id WHERE u.role IN ('AUTHORIZED_PERSONNEL','PNP') ORDER BY u.created_at DESC"), q("SELECT u.id,u.full_name AS \"fullName\",u.email,u.status,u.created_at AS \"createdAt\",t.id AS \"todaId\",t.name AS \"todaName\" FROM users u JOIN todas t ON t.president_user_id=u.id WHERE u.role='TODA_PRESIDENT' ORDER BY u.created_at DESC")]); res.json({ students, drivers, personnel, presidents }); } catch (e) { next(e); } });
app.delete("/admin/users/:id", auth, rolesOnly("SUPERADMIN"), async (req, res, next) => { try { if (req.params.id === req.user.id) error(400, "The active superadmin account cannot be deleted."); const target = await one("SELECT id,role FROM users WHERE id=$1", [req.params.id]); if (!target) error(404, "Account not found."); if (target.role === "SUPERADMIN") error(403, "Superadmin accounts cannot be deleted."); await transaction(async (client) => { await q("DELETE FROM users WHERE id=$1", [target.id], client); await audit(req.user.id, "USER_DELETE", "users", target.id, null, client); }); res.json({ ok: true, status: "DELETED" }); } catch (e) { next(e); } });
app.get("/admin/dashboard", auth, rolesOnly("SUPERADMIN"), async (_req, res, next) => { try { const count = async (sql) => Number((await one(sql)).count); const stats = { totalUsers: await count("SELECT COUNT(*) FROM users"), students: await count("SELECT COUNT(*) FROM users WHERE role='STUDENT'"), personnel: await count("SELECT COUNT(*) FROM users WHERE role='AUTHORIZED_PERSONNEL'"), drivers: await count("SELECT COUNT(*) FROM drivers WHERE is_active=1"), reports: await count("SELECT COUNT(*) FROM complaints"), pendingReports: await count("SELECT COUNT(*) FROM complaints WHERE status IN ('SUBMITTED','RECEIVED','UNDER_REVIEW','REFERRED')"), resolvedReports: await count("SELECT COUNT(*) FROM complaints WHERE status IN ('RESOLVED','CLOSED')"), violations: await count("SELECT COUNT(*) FROM violations") }; const reports = await q("SELECT c.reference_number AS id,c.location,cat.name AS category,c.status,c.created_at AS received,d.tricycle_identifier AS reference,LEFT(c.description,120) AS subject FROM complaints c JOIN complaint_categories cat ON cat.id=c.category_id JOIN drivers d ON d.id=c.driver_id ORDER BY c.created_at DESC LIMIT 50"); const activity = await q("SELECT a.action,a.target_type AS \"targetType\",a.created_at AS \"createdAt\",COALESCE(u.full_name,'System') AS actor FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 25"); res.json({ stats, reports, activity }); } catch (e) { next(e); } });
app.post("/seed", auth, rolesOnly("SUPERADMIN"), async (_req, res, next) => { try { const hash = await bcrypt.hash(process.env.SEED_PASSWORD || "Password123!", 12); await q("INSERT INTO users (id,full_name,email,username,password_hash,role) VALUES ($1,'Super Administrator','superadmin@oldsagay.gov.ph','superadmin',$2,'SUPERADMIN') ON CONFLICT DO NOTHING", ["00000000-0000-4000-8000-000000000000", hash]); await q("INSERT INTO todas (id,name,barangay,city,province) VALUES (1,'Old Sagay TODA','Old Sagay','Sagay City','Negros Occidental') ON CONFLICT DO NOTHING"); for (const name of ["Overcharging", "Reckless Driving", "Refusal to Transport", "Discourteous Behavior", "Unsafe Driving", "Vehicle Condition", "Other"]) await q("INSERT INTO complaint_categories (name) VALUES ($1) ON CONFLICT DO NOTHING", [name]); res.json({ ok: true, seededPassword: process.env.SEED_PASSWORD ? undefined : "Password123!" }); } catch (e) { next(e); } });

app.use((req, _res, next) => next(Object.assign(new Error("Route not found."), { status: 404 })));
app.use((err, _req, res, _next) => { console.error(err); const status = Number(err.status || (err.code === "23505" ? 409 : 500)); const message = status === 500 ? "The request could not be completed." : err.message; res.status(status).json({ error: { message, ...(err.issues ? { issues: err.issues } : {}) } }); });

export default app;
